[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "web_travel"
version = "0.2"
authors = [
  { name="Denislav Dimitrov", email="denislav.dimitrov@mail.bg" },
]
description = "Travel Journal Web Solution"
requires-python = ">=3.13"
dependencies = ["flask>3.1", "Flask-SQLAlchemy>3.1", "psycopg2-binary", "Flask-Mail",
    "pyjwt>2", "flask-ckeditor", "requests", "Pillow", ]

[project.optional-dependencies]
test = ["pytest>=7.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
cache_dir = ".pytest_cache"

[project.urls]
Homepage = "https://github.com/DenislavD/web-travel-journal"
Issues = "https://github.com/DenislavD/web-travel-journal/issues"

