[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "web_travel"
version = "0.1"
authors = [
  { name="Denislav Dimitrov", email="denislav.dimitrov@mail.bg" },
]
description = "Travel Journal Web Solution"
requires-python = ">=3.13"
dependencies = ["flask>3.1", ]

[project.scripts]
web_travel = "web_travel.app:app"

[project.optional-dependencies]
test = ["pytest>=7.0"]

[tool.pytest.ini_options]
testpaths = ["web_travel/tests"]
cache_dir = ".pytest_cache"

[project.urls]
Homepage = "https://github.com/DenislavD/web-travel-journal"
Issues = "https://github.com/DenislavD/web-travel-journal/issues"

